# permissions for end users to edit links.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: link-editor-role
rules:
- apiGroups:
  - kubepoint.io
  resources:
  - links
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepoint.io
  resources:
  - links/status
  verbs:
  - get
