# permissions for end users to view links.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: link-viewer-role
rules:
- apiGroups:
  - kubepoint.io
  resources:
  - links
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubepoint.io
  resources:
  - links/status
  verbs:
  - get
